"use client";
import { useState } from "react";
import { Download, KeyRound, Trash2 } from "lucide-react";
import { useKeypairs } from "@/hooks/use-keypairs";
import { CopyField } from "@/components/forms/copy-field";
import { GeneratorCard } from "./generator-card";

export function GenerateTool() {
  const { records, pending, error, generate, remove, download } = useKeypairs();
  const [label, setLabel] = useState("");
  const [passphrase, setPassphrase] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); const record = await generate({ label, passphrase }); setNotice(`Created ${record.publicKey}`); setLabel(""); setPassphrase(""); }
  return <div className="grid gap-6 xl:grid-cols-[420px_1fr]"><GeneratorCard><form onSubmit={submit} className="space-y-4"><div><label className="text-sm font-semibold">Wallet label</label><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Rewards wallet" maxLength={48} className="mt-2 w-full rounded-xl border px-3 py-2"/></div><div><label className="text-sm font-semibold">Encryption passphrase</label><input type="password" value={passphrase} onChange={e=>setPassphrase(e.target.value)} minLength={12} required autoComplete="new-password" className="mt-2 w-full rounded-xl border px-3 py-2"/><p className="mt-1 text-xs text-slate-500">At least 12 characters. It is never transmitted or stored.</p></div><button disabled={pending} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-800 px-4 py-3 font-bold text-white disabled:opacity-60"><KeyRound className="size-4"/>{pending?"Generating securely…":"Generate Solana keypair"}</button>{(error||notice)&&<p className={`text-sm ${error?"text-red-600":"text-emerald-700"}`}>{error||notice}</p>}</form></GeneratorCard><section className="rounded-3xl border bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Encrypted vault</h2><p className="text-sm text-slate-500">{records.length}/25 keypairs stored in this browser</p></div><button onClick={download} disabled={!records.length} className="flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold disabled:opacity-40"><Download className="size-4"/>Backup</button></div><div className="mt-5 space-y-4">{records.length===0?<p className="rounded-2xl bg-slate-50 p-6 text-sm text-slate-500">No keypairs generated yet.</p>:records.map(record=><article key={record.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{record.label}</h3><p className="text-xs text-slate-500">Created {new Date(record.createdAt).toLocaleString("fi-FI")}</p></div><button onClick={()=>remove(record.id)} className="rounded-lg p-2 text-red-600" aria-label="Delete keypair"><Trash2 className="size-4"/></button></div><div className="mt-4"><CopyField value={record.publicKey}/></div><div className="mt-3 flex gap-2"><a href={`/faucets?wallet=${record.publicKey}`} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Use in faucet</a><a href={`/rewards?wallet=${record.publicKey}`} className="rounded-lg border px-3 py-2 text-xs font-bold">Claim rewards</a></div></article>)}</div></section></div>
}
