
CREATE TYPE "Role" AS ENUM ('OWNER','ADMIN','OPERATOR','ANALYST','AUDITOR','VIEWER');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"email" TEXT UNIQUE NOT NULL,"name" TEXT,"role" "Role" NOT NULL DEFAULT 'VIEWER',"walletAddress" TEXT UNIQUE,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP NOT NULL);
CREATE TABLE "Organization" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"slug" TEXT UNIQUE NOT NULL,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP NOT NULL);
CREATE TABLE "Membership" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'VIEWER',UNIQUE("userId","organizationId"));
CREATE TABLE "Asset" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"type" TEXT NOT NULL,"network" TEXT NOT NULL,"tokenAddress" TEXT,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"metadata" JSONB,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP NOT NULL);
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY,"actorId" TEXT,"organizationId" TEXT,"action" TEXT NOT NULL,"resource" TEXT NOT NULL,"resourceId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AiConversation" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"title" TEXT NOT NULL,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP NOT NULL);
CREATE TABLE "AiMessage" ("id" TEXT PRIMARY KEY,"conversationId" TEXT NOT NULL,"role" TEXT NOT NULL,"content" TEXT NOT NULL,"metadata" JSONB,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
