export const routes = {
  home: "/",
  dashboard: "/dashboard",
  dashboardAi: "/dashboard/ai",
  dashboardSkills: "/dashboard/skills",
  dashboardGenerator: "/dashboard/developer/generator",
  dashboardMerchant: "/dashboard/merchant",
  dashboardCrm: "/dashboard/crm",
  dashboardErp: "/dashboard/erp",
  dashboardArchitectures: "/dashboard/architectures",
  dashboardMerchantProducts: "/dashboard/merchant/shop/products",
  dashboardMerchantDevices: "/dashboard/merchant/devices",
  dashboardMerchantRenewables: "/dashboard/merchant/renewables",
  dashboardMerchantEnergy: "/dashboard/merchant/energy",
  dashboardMerchantCarbon: "/dashboard/merchant/carbon",
  dashboardMerchantTrade: "/dashboard/merchant/trade",
  dashboardMerchantMarketplace: "/dashboard/merchant/marketplace",
  dashboardMerchantMap: "/dashboard/merchant/map",
  dashboardMerchantWayfinder: "/dashboard/merchant/wayfinder",
  dashboardMerchantDonate: "/dashboard/merchant/donate",
  dashboardMerchantCrowdfunding: "/dashboard/merchant/crowdfunding",
  dashboardFaucet: "/dashboard/faucet",
  dashboardRewards: "/dashboard/rewards",
  wallet: "/wallet",
  payments: "/payments",
  swap: "/swap",
  bridge: "/bridge",
  explorer: "/explorer",
  marketplace: "/marketplace",
  energy: "/energy",
} as const;

export type AppRoute = (typeof routes)[keyof typeof routes];
