
CREATE TABLE IF NOT EXISTS "ClientAccount"(
 "id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'ACTIVE',
 "metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ClientAccount_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "ProsumerAccount"(
 "id" TEXT PRIMARY KEY,"clientId" TEXT,"organizationId" TEXT NOT NULL,"name" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'ACTIVE',
 "generationKwh" DOUBLE PRECISION NOT NULL DEFAULT 0,"consumptionKwh" DOUBLE PRECISION NOT NULL DEFAULT 0,
 "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "DashboardFeature"(
 "id" TEXT PRIMARY KEY,"organizationId" TEXT,"featureKey" TEXT NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,
 "configuration" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS "DashboardFeature_organizationId_featureKey_key" ON "DashboardFeature"("organizationId","featureKey");
