import { explorerRoutes } from "./explorer/index.js";
import { bridgeRoutes } from "./bridges.js";
import { swapRoutes } from "./swaps.js";
import { renewablePlatformRoutes } from "./renewable-platform.js";
import { tokenRoutes } from "./tokens.js";
import { paymentRoutes } from "./payments.js";
import { solanaInfrastructureRoutes } from "./solana-infrastructure.js";
import { rateRoutes } from "./rates.js";
import { hardwareRoutes } from "./hardware.js";
import { blockchainRoutes } from "./blockchain.js";
import { marketplaceOrderRoutes } from "./marketplace-orders.js";
import { aiOperationRoutes } from "./ai-operations.js";
import { systemRoutes } from "./system.js";
import { walletRoutes } from "./wallet.js";
import { renewableRoutes } from "./renewables.js";
import { marketplacePlatformRoutes } from "./marketplace-platform.js";
import { prosumerRoutes } from "./prosumers.js";
import { clientRoutes } from "./clients.js";
import { managementRoutes } from "./management.js";
import { adminRoutes } from "./admin.js";
import { checkoutRoutes } from "./checkout.js";
import { mailRoutes } from "./mail.js";
import { accessRoutes } from "./access.js";
import { subscriptionRoutes } from "./subscriptions.js";
import { crowdfundingRoutes } from "./crowdfunding.js";
import { analyticsRoutes } from "./analytics.js";
import { smartMeterRoutes } from "./iot/smart-meters.js";
import { energyActorRoutes } from "./energy/actors.js";
import { userRoutes } from "./users.js";
import { rewardRoutes } from "./rewards.js";
import { aiModelRoutes } from "./ai-models/index.js";
import { locationRoutes } from "./locations/index.js";
import { trustedTokenRoutes } from "./tokens/trusted.js";
import { corsRoutes } from "./cors/index.js";
import { webhookRoutes } from "./webhooks/index.js";

import type { FastifyInstance } from "fastify";
import { aiRoutes } from "./ai.js";
import { healthRoutes } from "./health.js";
import { marketRoutes } from "./market.js";
import { newsletterRoutes } from "./newsletter.js";
import { portfolioRoutes } from "./portfolio.js";
import { solanaRoutes } from "./solana.js";
import { uploadRoutes } from "./uploads.js";
import { deviceRoutes } from "./iot/devices.js";
import { depinRoutes } from "./depin/nodes.js";
import { energyRoutes } from "./energy/markets.js";
import { tradeRoutes } from "./trade/orders.js";
import { x402Routes } from "./payments/x402.js";
import { energyMarketplaceRoutes } from "./energy/marketplace.js";
import { fundingRoutes } from "./funding.js";
import { saasRoutes } from "./saas.js";
import { authRoutes } from "./auth.js";

export async function apiV1(app: FastifyInstance) {
  await app.register(explorerRoutes);
  await app.register(webhookRoutes);
  await app.register(healthRoutes);
  await app.register(portfolioRoutes);
  await app.register(marketRoutes);
  await app.register(newsletterRoutes);
  await app.register(aiRoutes);
  await app.register(solanaRoutes);
  await app.register(uploadRoutes);
  await app.register(deviceRoutes);
  await app.register(depinRoutes);
  await app.register(energyRoutes);
  await app.register(tradeRoutes);
  await app.register(x402Routes);
  await app.register(energyMarketplaceRoutes);
  await app.register(fundingRoutes);
  await app.register(saasRoutes);
  await app.register(authRoutes);
  await app.register(corsRoutes);
  await app.register(trustedTokenRoutes);
  await app.register(locationRoutes);
  await app.register(aiModelRoutes);
  await app.register(rewardRoutes);
  await app.register(userRoutes);
  await app.register(energyActorRoutes);
  await app.register(smartMeterRoutes);
  await app.register(analyticsRoutes);
  await app.register(crowdfundingRoutes);
  await app.register(subscriptionRoutes);
  await app.register(accessRoutes);
  await app.register(mailRoutes);
  await app.register(checkoutRoutes);
  await app.register(adminRoutes);
  await app.register(managementRoutes);
  await app.register(clientRoutes);
  await app.register(prosumerRoutes);
  await app.register(marketplacePlatformRoutes);
  await app.register(renewableRoutes);
  await app.register(walletRoutes);
  await app.register(systemRoutes);
  await app.register(aiOperationRoutes);
  await app.register(marketplaceOrderRoutes);
  await app.register(blockchainRoutes);
  await app.register(hardwareRoutes);
  await app.register(rateRoutes);
  await app.register(solanaInfrastructureRoutes);
  await app.register(paymentRoutes);
  await app.register(bridgeRoutes);
  await app.register(swapRoutes);
  await app.register(renewablePlatformRoutes);
  await app.register(tokenRoutes);
}
